//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.02 at 10:49:47 PM COT 
//


package com.tecsup.gestion.ws.soap.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="employeeXSD" type="{http://www.tecsup.gestion/EmployeeSchema}EmployeeXSD"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "employeeXSD"
})
@XmlRootElement(name = "getEmployeeResponse")
public class GetEmployeeResponse {

    @XmlElement(required = true)
    protected EmployeeXSD employeeXSD;

    /**
     * Gets the value of the employeeXSD property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeXSD }
     *     
     */
    public EmployeeXSD getEmployeeXSD() {
        return employeeXSD;
    }

    /**
     * Sets the value of the employeeXSD property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeXSD }
     *     
     */
    public void setEmployeeXSD(EmployeeXSD value) {
        this.employeeXSD = value;
    }

}
